{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "cybersource",
    "contact": {}
  },
  "host": "localhost:3000",
  "basePath": "/api/v1",
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/aggregators/register": {
      "post": {
        "summary": "register aggregator",
        "tags": ["aggregators"],
        "operationId": "registeraggregator",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/registeraggregatorrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/aggregators/verify": {
      "post": {
        "summary": "verification & password creation",
        "tags": ["aggregators"],
        "operationId": "verification&passwordcreation",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/verification%26passwordcreationrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/aggregators/resend_otp": {
      "post": {
        "summary": "resend otp",
        "tags": ["aggregators"],
        "operationId": "resendotp",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/resendotprequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/aggregators/1": {
      "get": {
        "summary": "get by id",
        "tags": ["aggregators"],
        "operationId": "getbyid",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/login": {
      "post": {
        "summary": "login aggregator",
        "tags": ["aggregators"],
        "operationId": "loginaggregator",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginaggregatorrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators": {
      "get": {
        "summary": "all aggregators (admin only)",
        "tags": ["aggregators"],
        "operationId": "allaggregators(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/approve": {
      "patch": {
        "summary": "approve aggregator",
        "tags": ["aggregators"],
        "operationId": "approveaggregator",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/transactions": {
      "get": {
        "summary": "aggrator's transactions (accessible to the aggregator and admin)",
        "tags": ["aggregators"],
        "operationId": "aggrator'stransactions(accessibletotheaggregatorandadmin)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "transactionId",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "from",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "to",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/merchants": {
      "get": {
        "summary": "aggregator's merchants (allows owner and admin)",
        "tags": ["aggregators"],
        "operationId": "aggregator'smerchants(allowsownerandadmin)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "accountNumber",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/transactions/stats": {
      "get": {
        "summary": "Stats for aggregator transactions",
        "tags": ["aggregators"],
        "operationId": "Statsforaggregatortransactions",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/pending": {
      "get": {
        "summary": "pending aggregators (admin only)",
        "tags": ["aggregators"],
        "operationId": "pendingaggregators(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/activate": {
      "patch": {
        "summary": "activate aggregator (allows admin only)",
        "tags": ["aggregators"],
        "operationId": "activateaggregator(allowsadminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/deactivate": {
      "patch": {
        "summary": "deactivate aggregator (allows admin only)",
        "tags": ["aggregators"],
        "operationId": "deactivateaggregator(allowsadminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/aggregators/1/basic_info": {
      "get": {
        "summary": "aggregator basic_info (public)",
        "tags": ["aggregators"],
        "operationId": "aggregatorbasic_info(public)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/register": {
      "post": {
        "summary": "register merchant",
        "tags": ["merchants"],
        "operationId": "registermerchant",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/registermerchantrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/verify": {
      "post": {
        "summary": "verify merchant & create password",
        "tags": ["merchants"],
        "operationId": "verifymerchant&createpassword",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/verifymerchant%26createpasswordrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/resend_otp": {
      "post": {
        "summary": "resend otp",
        "tags": ["merchants"],
        "operationId": "Postresendotp",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/resendotprequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/login": {
      "post": {
        "summary": "login merchant",
        "tags": ["merchants"],
        "operationId": "loginmerchant",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginmerchantrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/1": {
      "get": {
        "summary": "get by id",
        "tags": ["merchants"],
        "operationId": "Getgetbyid",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants": {
      "get": {
        "summary": "all merchants (admin only)",
        "tags": ["merchants"],
        "operationId": "allmerchants(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/1/transactions": {
      "get": {
        "summary": "merchant n transactions  (allows merchant n, merchant n's aggregator and admin)",
        "tags": ["merchants"],
        "operationId": "merchantntransactions(allowsmerchantn,merchantn'saggregatorandadmin)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "transactionId",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "from",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "to",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/1/transactions/stats": {
      "get": {
        "summary": "Stats for a merchant's tranactions (allows owner, owner's aggregator and admin)",
        "tags": ["merchants"],
        "operationId": "Statsforamerchant'stranactions(allowsowner,owner'saggregatorandadmin)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/1/activate": {
      "patch": {
        "summary": "activate merchant (allows merchant's aggregator only)",
        "tags": ["merchants"],
        "operationId": "activatemerchant(allowsmerchant'saggregatoronly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/1/deactivate": {
      "patch": {
        "summary": "deactivate merchant (allows merchant's aggregator only)",
        "tags": ["merchants"],
        "operationId": "deactivatemerchant(allowsmerchant'saggregatoronly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/merchants/8/approve": {
      "patch": {
        "summary": "approve merchant (admin only)",
        "tags": ["merchants"],
        "operationId": "approvemerchant(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "consumes": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/approvemerchant%28adminonly%29request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/pending": {
      "get": {
        "summary": "pending merchants (admin only)",
        "tags": ["merchants"],
        "operationId": "pendingmerchants(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/merchants/8/risk_level": {
      "patch": {
        "summary": "change merchant risk-level (admin only)",
        "tags": ["merchants"],
        "operationId": "changemerchantrisk-level(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "consumes": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/changemerchantrisk-level%28adminonly%29request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions": {
      "post": {
        "summary": "create transaction",
        "tags": ["transactions"],
        "operationId": "createtransaction",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/createtransactionrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "all transactions (admin only)",
        "tags": ["transactions"],
        "operationId": "alltransactions(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "from",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "to",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/count": {
      "get": {
        "summary": "total count  (groupby status | month)  (admin only)",
        "tags": ["transactions"],
        "operationId": "totalcount(groupbystatus|month)(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "groupby",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/by_external_aggregators": {
      "get": {
        "summary": "transactions for all aggregators ( EXCEPT socialpay and direct-merchant aggregtors) (admin only)",
        "tags": ["transactions"],
        "operationId": "transactionsforallaggregators(EXCEPTsocialpayanddirect-merchantaggregtors)(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/stats/by_external_aggregators": {
      "get": {
        "summary": "transaction stats for external aggregators (admin only)",
        "tags": ["transactions"],
        "operationId": "transactionstatsforexternalaggregators(adminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/admin/login": {
      "post": {
        "summary": "login admin",
        "tags": ["admin"],
        "operationId": "loginadmin",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginadminrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/admin/dashboard": {
      "get": {
        "summary": "admin dashboard data",
        "tags": ["admin"],
        "operationId": "admindashboarddata",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/admin/count/pending/users": {
      "get": {
        "summary": "get total pending [agg + merchants] (allows admin only)",
        "tags": ["admin"],
        "operationId": "gettotalpending[agg+merchants](allowsadminonly)",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/profile": {
      "get": {
        "summary": "user details",
        "tags": ["auth"],
        "operationId": "userdetails",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "registeraggregatorrequest": {
      "title": "registeraggregatorrequest",
      "example": {
        "companyName": "The Company1.0",
        "phoneNumber": "09065734215",
        "businessYears": 9,
        "email": "theemail14@email.com",
        "websiteLink": "www.the-website.com",
        "accountNumber": "0763239709",
        "bvn": "2635637434",
        "address": "No 2 Luke Skywall Street",
        "primaryContactName": "The Primary Name",
        "primaryContactTelephone": "08984347322",
        "primaryContactPhoneNumber": "08033473333",
        "primaryContactEmail": "theprimary@email.com",
        "secondaryContactName": "The Secondary Name",
        "secondaryContactTelephone": "08044334444",
        "secondaryContactPhoneNumber": "08055544555",
        "secondaryContactEmail": "thesecondary@email.com"
      },
      "type": "object",
      "properties": {
        "companyName": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "businessYears": {
          "type": "integer",
          "format": "int32"
        },
        "email": {
          "type": "string"
        },
        "websiteLink": {
          "type": "string"
        },
        "accountNumber": {
          "type": "string"
        },
        "bvn": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "primaryContactName": {
          "type": "string"
        },
        "primaryContactTelephone": {
          "type": "string"
        },
        "primaryContactPhoneNumber": {
          "type": "string"
        },
        "primaryContactEmail": {
          "type": "string"
        },
        "secondaryContactName": {
          "type": "string"
        },
        "secondaryContactTelephone": {
          "type": "string"
        },
        "secondaryContactPhoneNumber": {
          "type": "string"
        },
        "secondaryContactEmail": {
          "type": "string"
        }
      },
      "required": [
        "companyName",
        "phoneNumber",
        "businessYears",
        "email",
        "websiteLink",
        "accountNumber",
        "bvn",
        "address",
        "primaryContactName",
        "primaryContactTelephone",
        "primaryContactPhoneNumber",
        "primaryContactEmail",
        "secondaryContactName",
        "secondaryContactTelephone",
        "secondaryContactPhoneNumber",
        "secondaryContactEmail"
      ]
    },
    "verification&passwordcreationrequest": {
      "title": "verification&passwordcreationrequest",
      "example": {
        "email": "ext_aggregator_6@gmail.com",
        "otp": "76276",
        "password": "testing"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "otp": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": ["email", "otp", "password"]
    },
    "resendotprequest": {
      "title": "resendotprequest",
      "example": {
        "email": "ext_aggregator_6@gmail.com"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        }
      },
      "required": ["email"]
    },
    "loginaggregatorrequest": {
      "title": "loginaggregatorrequest",
      "example": {
        "email": "socialpay@gmail.com",
        "password": "testing"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": ["email", "password"]
    },
    "registermerchantrequest": {
      "title": "registermerchantrequest",
      "example": {
        "agid": "ACCESSNG0000002",
        "companyName": "merchant 8",
        "phoneNumber": "09065734222",
        "email": "merchant_80@email.com",
        "accountNumber": "0875314409",
        "bvn": "2635637431",
        "businessYears": 9,
        "websiteLink": "www.the-website.com",
        "address": "No 2 Luke Skywall Street",
        "primaryContactName": "The Primary Name",
        "primaryContactTelephone": "08984347322",
        "primaryContactPhoneNumber": "08033473333",
        "primaryContactEmail": "theprimary@email.com",
        "secondaryContactName": "The Secondary Name",
        "secondaryContactTelephone": "08044334444",
        "secondaryContactPhoneNumber": "08055544555",
        "secondaryContactEmail": "thesecondary@email.com"
      },
      "type": "object",
      "properties": {
        "agid": {
          "type": "string"
        },
        "companyName": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "accountNumber": {
          "type": "string"
        },
        "bvn": {
          "type": "string"
        },
        "businessYears": {
          "type": "integer",
          "format": "int32"
        },
        "websiteLink": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "primaryContactName": {
          "type": "string"
        },
        "primaryContactTelephone": {
          "type": "string"
        },
        "primaryContactPhoneNumber": {
          "type": "string"
        },
        "primaryContactEmail": {
          "type": "string"
        },
        "secondaryContactName": {
          "type": "string"
        },
        "secondaryContactTelephone": {
          "type": "string"
        },
        "secondaryContactPhoneNumber": {
          "type": "string"
        },
        "secondaryContactEmail": {
          "type": "string"
        }
      },
      "required": [
        "agid",
        "companyName",
        "phoneNumber",
        "email",
        "accountNumber",
        "bvn",
        "businessYears",
        "websiteLink",
        "address",
        "primaryContactName",
        "primaryContactTelephone",
        "primaryContactPhoneNumber",
        "primaryContactEmail",
        "secondaryContactName",
        "secondaryContactTelephone",
        "secondaryContactPhoneNumber",
        "secondaryContactEmail"
      ]
    },
    "verifymerchant&createpasswordrequest": {
      "title": "verifymerchant&createpasswordrequest",
      "example": {
        "email": "merchant_80@email.com",
        "otp": "23025",
        "password": "testing"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "otp": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": ["email", "otp", "password"]
    },
    "loginmerchantrequest": {
      "title": "loginmerchantrequest",
      "example": {
        "email": "merchant_1@email.com",
        "password": "testing"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": ["email", "password"]
    },
    "approvemerchant(adminonly)request": {
      "title": "approvemerchant(adminonly)request",
      "example": {
        "riskLevel": "medium"
      },
      "type": "object",
      "properties": {
        "riskLevel": {
          "type": "string"
        }
      },
      "required": ["riskLevel"]
    },
    "changemerchantrisk-level(adminonly)request": {
      "title": "changemerchantrisk-level(adminonly)request",
      "example": {
        "riskLevel": "medium"
      },
      "type": "object",
      "properties": {
        "riskLevel": {
          "type": "string"
        }
      },
      "required": ["riskLevel"]
    },
    "createtransactionrequest": {
      "title": "createtransactionrequest",
      "example": {
        "merchantId": 1,
        "transactionId": "0000000000000001",
        "mid": "ACCESSNG000002",
        "amount": "1000.00",
        "cardHolder": "jon snow",
        "ip": "10.2.9.235",
        "type": "VERVE",
        "status": "SUCCESSFUL",
        "reconciliationId": "2828982slkflaf289282fss"
      },
      "type": "object",
      "properties": {
        "merchantId": {
          "type": "integer",
          "format": "int32"
        },
        "transactionId": {
          "type": "string"
        },
        "mid": {
          "type": "string"
        },
        "amount": {
          "type": "string"
        },
        "cardHolder": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "reconciliationId": {
          "type": "string"
        }
      },
      "required": [
        "merchantId",
        "transactionId",
        "mid",
        "amount",
        "cardHolder",
        "ip",
        "type",
        "status",
        "reconciliationId"
      ]
    },
    "loginadminrequest": {
      "title": "loginadminrequest",
      "example": {
        "username": "valid_username",
        "password": "valid_password"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": ["username", "password"]
    }
  },
  "tags": [
    {
      "name": "aggregators"
    },
    {
      "name": "merchants"
    },
    {
      "name": "transactions"
    },
    {
      "name": "admin"
    },
    {
      "name": "auth"
    }
  ]
}
